import { describe, expect, it } from 'vitest';
import { applyActiveEffects, triggerEffects } from './effects';
import { createCombatState } from './rotation';
import { trainingAttacker, trainingSupport } from '../data/agents/fixtures';
import { trainingDummy } from '../data/enemies';
import type { EffectDefinition } from './types';
const meta={gameVersion:'test',source:'test',lastVerified:'test',verified:true};

describe('effect engine',()=>{
  it('TEAM afeta qualquer membro e SELF só a fonte',()=>{let s=createCombatState([trainingSupport,trainingAttacker],trainingDummy);const teamEffect=trainingSupport.coreEffects[0];s=triggerEffects(s,[teamEffect],trainingSupport.id,'onEXSpecial').state;const target=applyActiveEffects(trainingAttacker.baseStats,trainingDummy,s,trainingAttacker.id);expect(target.stats.dmgBonus).toBeCloseTo(.3);const self:EffectDefinition={...teamEffect,id:'self',target:'SELF'};s=triggerEffects({...s,activeEffects:[]},[self],trainingSupport.id,'onEXSpecial').state;expect(applyActiveEffects(trainingAttacker.baseStats,trainingDummy,s,trainingAttacker.id).stats.dmgBonus).toBe(0);expect(applyActiveEffects(trainingSupport.baseStats,trainingDummy,s,trainingSupport.id).stats.dmgBonus).toBeCloseTo(.3)});
  it('ACTIVE_CHARACTER não vaza para off-field',()=>{const e:EffectDefinition={id:'active',name:'a',description:'',sourceType:'manual',trigger:'manual',target:'ACTIVE_CHARACTER',modifiers:[{stat:'dmgBonus',value:.2}],duration:10,meta};let s=createCombatState([trainingSupport,trainingAttacker],trainingDummy);s=triggerEffects(s,[e],trainingSupport.id,'manual').state;expect(applyActiveEffects(trainingSupport.baseStats,trainingDummy,s,trainingSupport.id).stats.dmgBonus).toBeCloseTo(.2);expect(applyActiveEffects(trainingAttacker.baseStats,trainingDummy,s,trainingAttacker.id).stats.dmgBonus).toBe(0)});
  it('SPECIFIC_CHARACTER respeita id',()=>{const e:EffectDefinition={id:'specific',name:'a',description:'',sourceType:'manual',trigger:'manual',target:'SPECIFIC_CHARACTER',specificCharacterId:trainingAttacker.id,modifiers:[{stat:'critDmg',value:.4}],meta};let s=createCombatState([trainingSupport,trainingAttacker],trainingDummy);s=triggerEffects(s,[e],trainingSupport.id,'manual').state;expect(applyActiveEffects(trainingAttacker.baseStats,trainingDummy,s,trainingAttacker.id).stats.critDmg).toBeCloseTo(1.8);expect(applyActiveEffects(trainingSupport.baseStats,trainingDummy,s,trainingSupport.id).stats.critDmg).toBeCloseTo(.5)});
  it('stacks até max e expira',()=>{const e:EffectDefinition={id:'stack',name:'stack',description:'',sourceType:'manual',trigger:'onHit',target:'SELF',modifiers:[{stat:'dmgBonus',value:.1}],duration:5,maxStacks:3,meta};let s=createCombatState([trainingAttacker],trainingDummy);for(let i=0;i<5;i++)s=triggerEffects(s,[e],trainingAttacker.id,'onHit').state;expect(s.activeEffects[0].stacks).toBe(3);expect(applyActiveEffects(trainingAttacker.baseStats,trainingDummy,s,trainingAttacker.id).stats.dmgBonus).toBeCloseTo(.8);s={...s,currentTime:6};expect(applyActiveEffects(trainingAttacker.baseStats,trainingDummy,s,trainingAttacker.id).stats.dmgBonus).toBeCloseTo(.5)});
  it('extend acumula duração e cooldown bloqueia retrigger',()=>{const e:EffectDefinition={id:'cd',name:'cd',description:'',sourceType:'manual',trigger:'manual',target:'SELF',modifiers:[{stat:'dmgBonus',value:.1}],duration:2,reapply:'extend',cooldown:1,meta};let s=createCombatState([trainingAttacker],trainingDummy);s=triggerEffects(s,[e],trainingAttacker.id,'manual').state;s={...s,currentTime:.5};s=triggerEffects(s,[e],trainingAttacker.id,'manual').state;expect(s.activeEffects[0].expiresAt).toBe(2);s={...s,currentTime:1.1};s=triggerEffects(s,[e],trainingAttacker.id,'manual').state;expect(s.activeEffects[0].expiresAt).toBe(4)});
});
